###############################################################################
#
#  Copyright (C) typedef int GmbH
#  SPDX-License-Identifier: MIT
#
###############################################################################
"""check.py: each house-standard rule's verdict, and the CLI contract."""

from __future__ import annotations

import json

import pytest
from check import FAIL, OK, WARN, inspect_repo
from conftest import GOOD_PYPROJECT, run_script

HEADER = "# Copyright (C) typedef int GmbH\n# SPDX-License-Identifier: MIT\n"


def _verdicts(repo):
    return {f.rule: f.status for f in inspect_repo(repo)}


def test_compliant_package(package):
    repo = package(
        **{
            "src/pkg/core.py": HEADER + "X = 1\n",
            "src/pkg/__init__.py": HEADER + '"""Pkg."""\n',
        }
    )
    assert set(_verdicts(repo).values()) == {OK}


@pytest.mark.parametrize(
    ("old", "new", "rule", "status"),
    [
        (
            'build-backend = "hatchling.build"',
            'build-backend = "setuptools.build_meta"',
            "build-backend",
            FAIL,
        ),
        ('requires = ["hatchling"]', 'requires = "hatchling"', "build-backend", FAIL),
        ('version = "26.10.1"', 'version = "1.2.3"', "version", OK),  # 1.2.3 parses
        ('version = "26.10.1"', 'version = "26.10.0"', "version", FAIL),
        ('version = "26.10.1"', 'version = "latest"', "version", FAIL),
        (
            'requires-python = ">=3.11"',
            'requires-python = ">=3.9"',
            "requires-python",
            FAIL,
        ),
        ('requires-python = ">=3.11"', "", "requires-python", WARN),
        ('license = "MIT"', "", "license", WARN),
        (
            'license = "MIT"',
            'license = "EUPL-1.2"',
            "license",
            WARN,
        ),  # a deviation from the house standard (#12)
        ('license = "MIT"', 'license = "LicenseRef-Proprietary"', "license", OK),
    ],
)
def test_rules(package, old, new, rule, status):
    repo = package(**{"pyproject.toml": GOOD_PYPROJECT.replace(old, new)})
    assert _verdicts(repo)[rule] == status


def test_headers_warn_until_every_non_generated_file_has_one(package):
    repo = package()
    assert _verdicts(repo)["spdx-headers"] == WARN
    gen = "# automatically generated by the FlatBuffers compiler, do not modify\n"
    repo = package(
        name="gen",
        **{
            "src/gen/__init__.py": HEADER,
            "src/gen/core.py": HEADER,
            "src/gen/fb/__init__.py": "",
            "src/gen/fb/T.py": gen,
        },
    )
    assert _verdicts(repo)["spdx-headers"] == OK  # the generated tree is exempt


def test_missing_or_broken_pyproject_fails(package):
    assert _verdicts(package(**{"pyproject.toml": None})) == {"pyproject": FAIL}
    assert _verdicts(package(**{"pyproject.toml": "[broken"})) == {"pyproject": FAIL}


def test_cli_exit_code_and_json(package):
    ok = package(**{"src/pkg/core.py": HEADER, "src/pkg/__init__.py": HEADER})
    bad = package(
        name="bad",
        **{
            "pyproject.toml": GOOD_PYPROJECT.replace(
                "hatchling.build", "setuptools.build_meta"
            )
        },
    )
    assert run_script("check.py", str(ok)).returncode == 0
    proc = run_script("check.py", "--json", str(ok), str(bad))
    assert proc.returncode == 1
    payload = json.loads(proc.stdout)
    assert payload["pkg"]["verdict"] == OK
    assert payload["bad"]["verdict"] == FAIL
