###############################################################################
#
#  Copyright (C) typedef int GmbH
#  SPDX-License-Identifier: MIT
#
###############################################################################
"""reconcile.py: the ChangeSet, its determinism, and today's license behaviour."""

from __future__ import annotations

import json

from conftest import GOOD_PYPROJECT, run_script
from reconcile import reconcile_repo

from _pp import PROPRIETARY, house_header

EMPTY_DIGEST = "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945"
GEN = "# automatically generated by the FlatBuffers compiler, do not modify\n"


def test_headers_for_unheadered_non_generated_sources_only(package):
    repo = package(
        **{
            "src/pkg/done.py": "# Copyright (C) typedef int GmbH\nY = 2\n",
            "src/pkg/fb/__init__.py": "",
            "src/pkg/fb/T.py": GEN,
        }
    )
    result = reconcile_repo(repo)
    assert [op["path"] for op in result["changeset"]] == [
        "src/pkg/__init__.py",
        "src/pkg/core.py",
    ]
    op = result["changeset"][1]
    assert op == {
        "kind": "file_modify",
        "path": "src/pkg/core.py",
        "action": "prepend_header",
        "license": "MIT",
        "loc": 1,
        "header": house_header("MIT"),
    }
    assert result["decisions_required"] == []


def test_proprietary_header(package):
    repo = package(
        **{
            "pyproject.toml": GOOD_PYPROJECT.replace(
                'license = "MIT"', f'license = "{PROPRIETARY}"'
            )
        }
    )
    (op, _) = reconcile_repo(repo)["changeset"]
    assert "All rights reserved." in op["header"]
    assert f"SPDX-License-Identifier: {PROPRIETARY}" in op["header"]


def test_converged_is_the_empty_digest(package):
    header = house_header("MIT")
    repo = package(**{"src/pkg/__init__.py": header, "src/pkg/core.py": header})
    result = reconcile_repo(repo)
    assert result["changeset"] == []
    assert result["digest"] == EMPTY_DIGEST


def test_deterministic_across_runs(package):
    repo = package(**{"src/pkg/b.py": "B = 1\n", "src/pkg/a.py": "A = 1\n"})
    first = run_script("reconcile.py", "--json", str(repo))
    second = run_script("reconcile.py", "--json", str(repo))
    assert first.returncode == 0
    assert first.stdout == second.stdout  # byte-identical
    paths = [op["path"] for op in json.loads(first.stdout)["pkg"]["changeset"]]
    assert paths == sorted(paths)


def test_missing_license_raises_license_required(package):
    """Today's behaviour, pinned before S2 (#12) changes the license rule."""
    repo = package(**{"pyproject.toml": GOOD_PYPROJECT.replace('license = "MIT"', "")})
    result = reconcile_repo(repo)
    assert result["changeset"] == []
    (request,) = result["decisions_required"]
    assert request["type"] == "license_required"
    assert request["options"] == ["MIT", "EUPL-1.2", PROPRIETARY]


def test_reconcile_changes_nothing(package):
    repo = package()
    before = (repo / "src/pkg/core.py").read_text(encoding="utf-8")
    assert run_script("reconcile.py", str(repo)).returncode == 0
    assert (repo / "src/pkg/core.py").read_text(encoding="utf-8") == before
